version: 2
jobs:
   build:
     docker:
       - image: ubuntu:trusty
     steps:
       - checkout
       - run: 
           name: 【ビルド】gitとbcコマンドのインストール
           command: sudo apt-get update && sudo apt-get -y install bc git
       - run: 
           name: 【ビルド】bats(テスト用のライブラリ)のインストール
           command: git clone https://github.com/sstephenson/bats.git && cd bats && chmod a+x install.sh && sudo ./install.sh /usr/local
       - run: 
           name: 【テスト】任意の関数の単体テスト
           command: ./sample.sh
